import type { LucideIcon, LucideProps } from 'lucide-react-native';
import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Bell,
  Bike,
  BriefcaseBusiness,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock3,
  CreditCard,
  FileText,
  FolderOpen,
  Globe,
  Image,
  Landmark,
  LoaderCircle,
  Map,
  MapPin,
  MessageCircle,
  Package,
  Phone,
  Pin,
  Plus,
  Receipt,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Star,
  Target,
  Trash2,
  Upload,
  User,
  Wallet,
  X,
} from 'lucide-react-native';

export const mobileIcons = {
  banknote: Banknote,
  bell: Bell,
  bike: Bike,
  camera: Camera,
  car: Car,
  check: Check,
  success: CheckCircle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  alert: CircleAlert,
  help: CircleHelp,
  error: CircleX,
  tasks: ClipboardList,
  clock: Clock3,
  card: CreditCard,
  archive: Archive,
  briefcase: BriefcaseBusiness,
  document: FileText,
  folder: FolderOpen,
  globe: Globe,
  image: Image,
  landmark: Landmark,
  loading: LoaderCircle,
  map: Map,
  pin: MapPin,
  message: MessageCircle,
  package: Package,
  phone: Phone,
  location: Pin,
  mapPin: MapPin,
  plus: Plus,
  receipt: Receipt,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  star: Star,
  target: Target,
  delete: Trash2,
  upload: Upload,
  user: User,
  wallet: Wallet,
  close: X,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  clipboardList: ClipboardList,
} as const satisfies Record<string, LucideIcon>;

export type MobileIconName = keyof typeof mobileIcons;

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: MobileIconName;
  label?: string;
}

export function Icon({ name, label, size = 20, accessibilityLabel, ...props }: IconProps) {
  const Component = mobileIcons[name];
  return <Component size={size} accessibilityLabel={label ?? accessibilityLabel} {...props} />;
}
